main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.12.3
api-version: 1.13
author: ThizThizzyDizzy
website: "https://www.spigotmc.org/resources/thizzyz-tree-feller.64346/"
name: TreeFeller
commands:
    treefeller:
        description: TreeFeller commands
        usage: /treefeller help | toggle [on|off] | on | off | reload | debug [on|off]