main: com.thizthizzydizzy.treefeller.TreeFeller
version: 1.18.3
api-version: 1.16
author: ThizThizzyDizzy
website: "https://www.spigotmc.org/resources/thizzyz-tree-feller.64346/"
name: TreeFeller
commands:
    treefeller:
        description: TreeFeller commands
        usage: /treefeller (help|toggle [on|off]|on|off|reload|debug [on|off]|config)
softdepend:
  - mcMMO
  - CoreProtect
  - WorldGuard
  - WorldEdit
  - Towny
  - OreRegenerator
  - Drop2Inventory
  - Drop2InventoryPlus
  - Jobs
  - EcoSkills
  - LogBlock
  - Lands
  - PlaceholderAPI
  - SaberFactions